name: 'Dependency updater'
description: 'Update system dependencies of a Dockerfile'
inputs:
  dockerfile:
    description: 'Dockerfile path'
    required: true
    default: 'Dockerfile'
  dependencies:
    description: 'dependencies.json file path'
    required: true
    default: 'dependencies.json'
  apply:
    description: 'apply the potential update to the local code'
    required: true
    default: 'false'
outputs:
  updatedDependencies:
    description: "JSON representing the updated dependencies"
runs:
  using: 'node20'
  main: 'dist/index.js'
