name: 'Dependency updater'
description: 'Update system dependencies of a Dockerfile'
inputs:
  dockerfile:
    description: 'Dockerfile path'
    required: true
    default: 'Dockerfile'
  dependencies:
    description: 'dependencies.json file path'
    required: true
    default: 'dependencies.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
